<!DOCTYPE html> 
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="author" content="" />
		<meta name="copyright" content="" />
		<meta name="robots" content="index, follow" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
    <title>LAKO CMF Admin</title>
    
    <link rel="Shortcut Icon" href="favicon.ico" type="image/x-icon" />
		<link rel="stylesheet" href="css/print.css" type="text/css" media="print" />
		<link rel="stylesheet" href="css/screen.css" type="text/css" media="screen,projection" />
		<link rel="index" title="" href="" />
 
		<!--[if lt IE 9 ]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]--> 
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body { padding-top: 70px; }
    </style>
	</head>
  <body>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">LAKO</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
        <ul class="nav navbar-nav">
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <? lako::get('cmf')->templates->render('admin/menu', array('menu' => array())) ?>
      </div>
      <div class="col-md-10">