<? lako::get('cmf')->templates->render('admin/header') ?>
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <? lako::get('cmf')->templates->render('admin/menu', array('menu' => $data['menu'])) ?>
      </div>
      <div class="col-md-10">
        <p>&nbsp;</p>
        <h1 class="text-center">
          LAKO CMF
        </h1>
      </div>
    </div>
  </div>
<? lako::get('cmf')->templates->render('admin/footer') ?>